apiVersion: apps/v1
kind: Deployment
metadata:
  name: nogard
  labels:
    app: nogard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nogard
  template:
    metadata:
      labels:
        app: nogard
    spec:
      containers:
      - name: nogard
        image: ssouthcity/nogard
        envFrom:
        - secretRef:
            name: nogard-secrets
      - name: cache
        image: redis
        ports:
        - containerPort: 6379