---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nogard
  namespace: nogard
  labels:
    app: nogard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nogard
  template:
    metadata:
      labels:
        app: nogard
    spec:
      containers:
      - name: nogard
        image: $NOGARD_IMAGE
        imagePullPolicy: Always
        env:
        - name: NOGARD_TOKEN
          valueFrom:
            secretKeyRef:
              name: nogard-secret
              key: discord_token
        - name: NOGARD_COMPENDIUM_SHEET_ID
          valueFrom:
            secretKeyRef:
              name: nogard-secret
              key: compendium_sheet_id
        - name: NOGARD_COMPENDIUM_SHEET_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: nogard-secret
              key: compendium_sheet_credentials
      - name: cache
        image: redis
        ports:
        - "6379:6379"
