apiVersion: apps/v1
kind: Deployment
metadata:
  name: nogard
  labels:
    app: nogard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nogard
  template:
    metadata:
      labels:
        app: nogard
    spec:
      containers:
      - name: nogard
        image: ssouthcity/nogard
        args: 
        - "-redis=\"$REDIS_SRV_SERVICE_HOST:$REDIS_SRV_SERVICE_PORT\""
        envFrom:
        - secretRef:
            name: nogard-secrets
