apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- redis/deployment.yaml
- redis/volume.yaml
- redis/service.yaml
- redis/cronjob.yaml

namespace: nogard

secretGenerator:
- envs:
  - .env
  name: nogard-secrets
  type: Opaque

images:
- name: ssouthcity/nogard
  newTag: latest
