---
apiVersion: v1
kind: Secret
metadata:
  name: nogard-secret
  namespace: nogard
type: Opaque
data:
  discord_token: $NOGARD_TOKEN
  compendium_sheet_id: $NOGARD_COMPENDIUM_SHEET_ID
  compendium_sheet_credentials: $NOGARD_COMPENDIUM_SHEET_CREDENTIALS