name: Deploy Application

on:
  push:
    branches: [ "main" ]
    paths:
    - ".github/workflows/deploy.yaml"
    - "Dockerfile"
    - "k8s/**"
    - "**.go"
    - "cmd/nogard/**"
    - "!cmd/**"

env:
  DOCKER_REPOSITORY: ssouthcity/nogard

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'
    
    - name: Build application
      run: go build cmd/nogard/*
    
    - name: Run tests
      run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3

    - uses: docker/setup-qemu-action@v2

    - uses: docker/setup-buildx-action@v2
  
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3

    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}

    - name: Download kubeconfig
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 main-cluster
    
    - name: Encode token
      run: echo "NOGARD_TOKEN_BASE64=$(echo -n $NOGARD_TOKEN | base64 -w0)" >> $GITHUB_ENV
      env:
        NOGARD_TOKEN: ${{ secrets.NOGARD_TOKEN }}

    - name: Apply new configuration
      run: cat k8s/*.yaml | envsubst | kubectl apply -f -
      env:
        NOGARD_IMAGE: ${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}
        NOGARD_TOKEN: ${{ env.NOGARD_TOKEN_BASE64 }}
        NOGARD_COMPENDIUM_SHEET_ID: ${{ secrets.NOGARD_COMPENDIUM_SHEET_ID }}
        NOGARD_COMPENDIUM_SHEET_CREDENTIALS: ${{ secrets.NOGARD_COMPENDIUM_SHEET_CREDENTIALS }}
