name: Build and Push Application

on:
  push:
    branches: [ "main" ]
    paths:
    - ".github/workflows/docker.yaml"
    - "Dockerfile"
    - "**.go"
    - "cmd/nogard/**"
    - "!cmd/**"

env:
  DOCKER_REPOSITORY: ssouthcity/nogard

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'
    
    - name: Build application
      run: go build cmd/nogard/*
    
    - name: Run tests
      run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3

    - uses: docker/setup-qemu-action@v2

    - uses: docker/setup-buildx-action@v2
  
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}