name: Upsert Application Commands

on:
  push:
    branches: ["main"]
    paths: ["commands.json"]

jobs:
  upsert-cmds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run upsert utility
        run: make commands
        env:
          NOGARD_TOKEN: ${{ secrets.NOGARD_TOKEN }}
          NOGARD_APPLICATION_ID: ${{ secrets.NOGARD_APPLICATION_ID }}
